### ISSUE TITLE
Maven build tests fail on Ubuntu 16.04 with OpenJDK 1.8

### ISSUE THREAD

**Issue by basdusee** [rackerlabs/blueflood#806] opened 2017-05-04 09:45 UTC
Good morning,

The tests on blueflood masterbranch are not passing on my machine when running mvn test -X integration-test.
```java
testConfigTtl_valid(com.rackspacecloud.blueflood.cache.ConfigTtlProviderTest)  Time elapsed: 0.009 sec  <<< ERROR!
java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
        at com.rackspacecloud.blueflood.cache.ConfigTtlProviderTest.testConfigTtl_valid(ConfigTtlProviderTest.java:50)

testConfigTtlForStrings(com.rackspacecloud.blueflood.cache.ConfigTtlProviderTest)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.AssertionError
        at com.rackspacecloud.blueflood.cache.ConfigTtlProviderTest.testConfigTtlForStrings(ConfigTtlProviderTest.java:61)

Running com.rackspacecloud.blueflood.cache.SafetyTtlProviderTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec - in com.rackspacecloud.blueflood.cache.SafetyTtlProviderTest
Running com.rackspacecloud.blueflood.cache.CombinedTtlProviderTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in com.rackspacecloud.blueflood.cache.CombinedTtlProviderTest
Running com.rackspacecloud.blueflood.cache.LocatorCacheTest
Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 18.011 sec - in com.rackspacecloud.blueflood.cache.LocatorCacheTest

Results :

Failed tests:
  ConfigTtlProviderTest.testConfigTtlForStrings:61
Tests in error:
  ConfigTtlProviderTest.testConfigTtl_valid:50 » IllegalState Optional.get() can...

Tests run: 734, Failures: 1, Errors: 1, Skipped: 0
```
Disabling (commenting out actually) of the  com.rackspacecloud.blueflood.cache.ConfigTtlProviderTest.testConfigTtl_valid and com.rackspacecloud.blueflood.cache.ConfigTtlProviderTest.testConfigTtlForStrings works (of course) and maven finishes the blueflood-core tests without problems.

This smells like a Java 8 upgrading issue, because it is about Optionals, i think.

Specs:
```bash
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_121, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-75-generic", arch: "amd64", family: "unix"
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
```
I'm looking into it myself right now, but are not yet familiar with the code myself, nor with Optionals. I'll post a fix if I find one, but if somebody knows a fix already, please comment.

**Comment by shintasmith** [comment] 2017-05-04 14:48
Hi, @basdusee , Blueflood is not officially supported or tested with OpenJDK 8. We use Travis to run our tests and Travis also does not support OpenJDK 8. Have you tried this using OracleJDK 8?

**Comment by basdusee** [comment] 2017-05-04 17:16
Hi @shintasmith i just cleared the maven cache, tested it with OracleJDK 8 and got the same thing:

```java
Tests run: 4, Failures: 1, Errors: 1, Skipped: 0, Time elapsed: 0.014 sec <<< FAILURE! - in com.rackspacecloud.blueflood.cache.ConfigTtlProviderTest
testConfigTtl_valid(com.rackspacecloud.blueflood.cache.ConfigTtlProviderTest)  Time elapsed: 0.007 sec  <<< ERROR!
java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
        at com.rackspacecloud.blueflood.cache.ConfigTtlProviderTest.testConfigTtl_valid(ConfigTtlProviderTest.java:50)

testConfigTtlForStrings(com.rackspacecloud.blueflood.cache.ConfigTtlProviderTest)  Time elapsed: 0.003 sec  <<< FAILURE!
java.lang.AssertionError
        at com.rackspacecloud.blueflood.cache.ConfigTtlProviderTest.testConfigTtlForStrings(ConfigTtlProviderTest.java:61)
```

Before that only green lights, except for a small warning:

```java
log4j:WARN No appenders could be found for logger (com.rackspacecloud.blueflood.io.IOContainer).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```

It's the same output as with OpenJDK.

Java version:
```bash
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

**Comment by shintasmith** [comment] 2017-05-08 14:54
@basdusee , I'll look into this. My JDK8 is build 91, a little older. I will update and see if I can reproduce this on MacOS. Thx

**Comment by shintasmith** [comment] 2017-05-08 15:45
@basdusee , I'll look into this. My JDK8 is build 91, a little older. I will update and see if I can reproduce this on MacOS. Thx

**Comment by basdusee** [comment] 2017-05-08 15:50
@shintasmith Thank you for looking at this issue. Please let me know if you need more info from me.

Could this problem be due to some TTL values in the config file which I forgot to define, or something like that? In the current running Docker blueflood container with JDK 7 the following warnings are in the logs: "2017-05-06 12:34:00 DEBUG ConfigTtlProvider   :129 - No valid TTL entry for granularity: metrics_1440m, rollup type: BF_BASIC in config. Resorting to safe TTL values."

The Interwebz says that there first should be an .isPresent() before using a .get() when using Optionals, and else this error is raised if the value is Absent. Like in getTTL (line 125 et al in ConfigTtlProvider.java), there is a .get() but no .isPresent() check first...which maybe indicates some improvement possibility in this code but also that a TTL value is missing somewhere. I will check my config once again.

**Comment by shintasmith** [comment] 2017-05-08 16:34
@basdusee I am unable to reproduce this locally on my box using JDK8u131. 

Looking at the code, the Optional is only absent() if ```ttlMapper``` returns null for the granularity and rollupType:

https://github.com/rackerlabs/blueflood/blob/master/blueflood-core/src/main/java/com/rackspacecloud/blueflood/cache/ConfigTtlProvider.java#L126

But ```ttlMapper``` should've been initialized with the proper TTLs for FULL granularity and rollup type BF_BASIC in the ```ConfigTtlProviderTest.java```'s setup() method:

https://github.com/rackerlabs/blueflood/blob/master/blueflood-core/src/test/java/com/rackspacecloud/blueflood/cache/ConfigTtlProviderTest.java#L39

The test only checks for FULL granularity, not 1440m. So only TTL for the FULL granularity is needed for the test. 

I agree the code could be written better to handle the issue. But no matter what, the test will fail if the ```ttlMapper``` is not populated properly. 

Do you have a way to debug this from an IDE?

**Comment by basdusee** [comment] 2017-05-08 19:14
@shintasmith You mean IDE as in Eclipse or Netbeans? The repo is on a (virtual) server on our platform, and the "IDE" is now vim. If needed I could install an IDE on it and use X forwarding.

Wait I'm first going to check our server and repo, it's not a very logical error to happen and it's more likely that something local is not right.

**Comment by shintasmith** [comment] 2017-05-09 13:42
@basdusee , did you find anything? The test should be populating the TTL mappings properly via the call to ```System.setProperty()``` as I listed in the code above and the ConfigTtlProvider will fetch that from system property (done in the Configuration.java class). 

I am not clear why it's failling on your environment.

**Comment by basdusee** [comment] 2017-05-09 13:56
@shintasmith Sorry, it was a bit busy over here. I did clone the repo onto another Ubuntu machine (a local VM with a GUI so that makes it possible to use an IDE) and the test run gave the exact same results (failure) so it is almost definately an Ubuntu 16.04 related issue. Didn't got to setting up the IDE yet.

I also ran the tests on a CentOS 7 VM which we had laying around for test purposes, but unit tests passed without problems there. Same JDK8u131, but with an older maven (3.0.5.) Could this be Maven related? The test Cassandra server didn't spin up correctly on CentOS, but the unit test passed perfectly.

I will try to setup the IDE tonight and debug it properly (tonight as in European night, I'm in the Netherlands).

**Comment by shintasmith** [comment] 2017-05-09 14:27
@basdusee , I am using Maven 3.2.5. Yesterday, I noticed you were using the latest Maven 3.3.9. I tried Maven 3.3.9 locally and still could not reproduce your issue.

Based on your info on CentOS, my guess is that it's Ubuntu issue. Maybe some default security settings on JDK?

**Comment by shintasmith** [comment] 2017-05-09 14:46
@basdusee, I just run the tests on Ubuntu 14.04, using Maven 3.0.5 and OpenJDK 8u101. They are running fine. I am very perplexed!

**Comment by basdusee** [comment] 2017-05-09 15:08
@shintasmith Do you have Ubuntu 16.04 somewhere around? I'm also a little bit perplexed myself, it's running fine on anything but Ubuntu 16.04 with JDK8.
Ok, i'm going to deinstall the standard Ubuntu Maven and install the vanilla one from Apache. Maybe Ubuntu added a "feature" to it.

**Comment by basdusee** [comment] 2017-05-09 15:24
@shintasmith Nope, I downloaded Maven 3.5.0 from the Apache website and "installed" it (unpacked it). It's very nice with colors in the terminal, but still gives the same error. It's not maven related I think. This is very weird. I'm using the Oracle JDK (not Ubuntu's), the vanilla Maven and still errors...

We can go through with using CentOS by the way, but this is very mysterious. I'll try to fire up Netbeans this afternoon, maybe that will indicate something.

**Comment by shintasmith** [comment] 2017-05-10 18:08
@basdusee , I just got a chance to spin off an Unbuntu 16.04 and I am able to reproduce the issue there. I know what the problem is.

The issue is that the tests run on Ubuntu 16.04 in different order than on my Mac and probably on your CentOS. I don't know why they are in different order. But this causes ```ConfigTtlProvider``` to be initialized prematurely. I'm working on a fix. Thanks!

**Comment by basdusee** [comment] 2017-05-10 22:26
@shintasmith Thanks for addressing this issue and fixing it!

**Comment by shintasmith** [comment] 2017-05-11 14:06
@basdusee , the fix is on master. Closing this. Thanks!

**Closed by shintasmith** 2017-05-11 14:06 UTC
